# Generated by Django 5.2.8 on 2025-11-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponibile'), ('MAINTENANCE', 'In Manutenzione'), ('OUT_OF_SERVICE', 'Fuori Servizio')], default='AVAILABLE', max_length=20),
        ),
    ]
